sudo: required
dist: trusty
branches:
  # Only build master and tagged versions, i.e. not feature branches; feature
  # branches already get built after opening a pull request.
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
language: node_js
node_js:
  - "stable"
env:
  # Test against multiple versions of the PureScript compiler
  - PURS_TEST_VERSION=v0.12.3
  - PURS_TEST_VERSION=v0.12.5
install:
  - export PURS_BUILD_VERSION=v0.12.5
  - export PSC_PACKAGE_VERSION=v0.5.1
  - export PATH=$HOME/bin:$PATH
  - mkdir -p $HOME/bin

  # Download the PureScript compiler
  - |
    function download_purescript() {
      local DIR, VERSION
      VERSION=$1
      DIR=$HOME/bin/purescript-$VERSION
      mkdir $DIR
      wget -O $DIR/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$VERSION/linux64.tar.gz
      tar -xvf $DIR/purescript.tar.gz -C $DIR --strip-components 1 purescript/purs
      chmod a+x $DIR/purs
    }
  - download_purescript $PURS_BUILD_VERSION
  - |
    if [ "$PURS_BUILD_VERSION" != "$PURS_TEST_VERSION" ]
    then
      download_purescript $PURS_TEST_VERSION
    fi

  # Download psc-package
  - wget -O $HOME/bin/psc-package.tar.gz https://github.com/purescript/psc-package/releases/download/$PSC_PACKAGE_VERSION/linux64.tar.gz
  - tar -xvf $HOME/bin/psc-package.tar.gz -C $HOME/bin --strip-components 1 psc-package/psc-package
  - chmod a+x $HOME/bin/psc-package

  - travis_retry npm install -g bower
script:
  - PATH=$HOME/bin/purescript-$PURS_BUILD_VERSION:$PATH npm install
  - PATH=$HOME/bin/purescript-$PURS_TEST_VERSION:$PATH npm test
