sudo: required
dist: trusty
language: node_js
node_js:
  - "stable"
before_install:
  - travis_retry npm install -g bower
  - wget -q -O - https://github.com/purescript/psc-package/releases/download/v0.1.2/linux64.tar.gz | sudo tar xzf - -C /usr/local/bin --strip-components 1 psc-package/psc-package
script:
  - npm test
