# Test against this version of Node.js
environment:
  nodejs_version: "6.2"

# Cache bower packages.
# This should speed builds up, but more importantly, reduce errors during
# `bower install` (which are, unfortunately, quite frequent).
cache:
  - '%LOCALAPPDATA%\bower\cache\packages -> bower.json'

# Install scripts. (runs after repo cloning)
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - ps: Install-Product node (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install -g bower
  - npm install

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm run test

# "build" means "build using the project or solution file", which we don't
# have. So turn this off.
build: off
