# Test against this version of Node.js
environment:
  nodejs_version: "10"

# Only build master and tagged versions, i.e. not feature branches; feature
# branches already get built after opening a pull request.
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

# Only test on x64 machines (as we only provide x64 binaries).
platform:
  - x64

# Cache bower packages.
# This should speed builds up, but more importantly, reduce errors during
# `bower install` (which are, unfortunately, quite frequent).
cache:
  - '%LOCALAPPDATA%\bower\cache\packages -> bower.json'

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g bower
  - npm install
  - set PATH=%PATH%;C:\tools
  - pushd C:\tools & curl -opsc-package.tar.gz -L https://github.com/purescript/psc-package/releases/download/v0.2.2/win64.tar.gz & 7z e psc-package.tar.gz & 7z e psc-package.tar psc-package/psc-package.exe & popd

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm run test

# "build" means "build using the project or solution file", which we don't
# have. So turn this off.
build: off
